name: DEV Pipeline
on: 
  push:
  pull_request:
    branches: [main]
jobs:
  Hello:
    runs-on: self-hosted
    steps:
      - name: Say hello
        run: echo 'Hello'

  Checkout-Code:
    needs: Hello
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

  Install-and-Configure-Terraform:
    needs: Hello
    runs-on: self-hosted
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
  Run-Terraform:
    needs: [Checkout-Code,Install-and-Configure-Terraform]
    runs-on: self-hosted
    steps:
      - name: Terraform init
        run: terraform init
      - name: Terraform apply
        run: terraform apply -auto-approve
